###########################
#  Configuration
###########################

# Use vim key bindings
setw -g mode-keys vi

# Start indexes at 1
set -g base-index 1
setw -g pane-base-index 1

# Re-number and re-name windows dynamically
setw -g automatic-rename on
set -g renumber-windows on

# Enable the mouse
set -g mouse on

###########################
#  Key Bindings
###########################

# Prefix
unbind C-b
set -g prefix C-a

# Window splitting
unbind %
bind | split-window -h
unbind '"'
bind - split-window -v

###########################
#  Theme
###########################

# Nord theme
set -g @nord_tmux_no_patched_font "1"

###########################
#  Plugins
###########################

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin "arcticicestudio/nord-tmux"
set -g @plugin 'christoomey/vim-tmux-navigator'

run -b '~/.tmux/plugins/tpm/tpm'
