###########################
#  Configuration
###########################

# Set sane terminal capabilities
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Use vim key bindings
setw -g mode-keys vi

# Start indexes at 1
set -g base-index 1
setw -g pane-base-index 1

# Re-number and re-name windows dynamically
setw -g automatic-rename on
set -g renumber-windows on

# Enable the mouse
set -g mouse on

###########################
#  Key Bindings
###########################

# Set prefix to Ctrl-A
set-option -g prefix C-a
unbind-key C-a
bind-key C-a send-prefix

# Window splitting
unbind %
bind | split-window -h
unbind '"'
bind - split-window -v

###########################
#  Theme
###########################

set-option -g status-style bg=default

set -g status-left ' '
set -g status-right ''

setw -g window-status-current-format '#[underscore,bold]#I #W'
setw -g window-status-format '#I #W'
